# Generated by Django 3.2.9 on 2021-11-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentid', models.IntegerField(db_column='AppointmentID', primary_key=True, serialize=False)),
                ('starttime', models.DateField(blank=True, db_column='StartTime', null=True)),
                ('endtime', models.DateField(blank=True, db_column='EndTime', null=True)),
                ('cabinetnumber', models.IntegerField(blank=True, db_column='CabinetNumber', null=True)),
                ('comments', models.TextField(blank=True, db_column='Comments', null=True)),
            ],
            options={
                'db_table': 'Appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctorid', models.IntegerField(db_column='DoctorID', primary_key=True, serialize=False)),
                ('specialization', models.TextField(blank=True, db_column='Specialization', null=True)),
            ],
            options={
                'db_table': 'Doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientid', models.IntegerField(db_column='PatientID', primary_key=True, serialize=False)),
                ('insurancenumber', models.TextField(blank=True, db_column='InsuranceNumber', null=True)),
            ],
            options={
                'db_table': 'Patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personaldata',
            fields=[
                ('personaldataid', models.IntegerField(db_column='PersonalDataID', primary_key=True, serialize=False)),
                ('firstname', models.TextField(blank=True, db_column='FirstName', null=True)),
                ('lastname', models.TextField(blank=True, db_column='LastName', null=True)),
                ('phone', models.TextField(blank=True, db_column='Phone', null=True)),
                ('email', models.TextField(blank=True, db_column='Email', null=True)),
            ],
            options={
                'db_table': 'PersonalData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationid', models.IntegerField(db_column='ReservationID', primary_key=True, serialize=False)),
                ('starttime', models.DateField(blank=True, db_column='StartTime', null=True)),
                ('endtime', models.DateField(blank=True, db_column='EndTime', null=True)),
            ],
            options={
                'db_table': 'Reservation',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
