# Generated by Django 3.2.9 on 2021-12-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211118_2225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='Appointment',
        ),
    ]
